Repository cryostatio/cryostatio.github.io, pull requests merged in 2023-05, with the labels that each got.

#110 feat(blog): add Introspective Investigation post
  _posts/2023-05-03-agent-threads-investigation.md
  images/blog/introspective-investigation-jmc.png
Labels: feat

#111 chore(versions): bump supported platform versions
  _data/versions.yaml
  _layouts/home.html
Labels: documentation

#115 docs(getting-started): update sample app example
  get-started/index.md
Labels: documentation

#113 docs(auth): remove outdated Bearer form, add details on OpenShift and Basic mechanisms
  get-started/index.md
  images/token-auth-page.png
Labels: documentation

#119 feat(cred): document credentials testing table
  guides/_subsections/store-credentials.md
  images/2.3.0/store-credentials-3.png
Labels: docs

#118 feat(topology): document topology view and custom target form
  guides/_subsections/common/navigate-to-topology.md
  guides/_subsections/create-a-custom-target.md
  guides/_subsections/create-an-automated-rule.md
  guides/_subsections/use-topology-view.md
  guides/index.md
  images/2.3.0/custom-target-1.png
  images/2.3.0/custom-target-2.png
  images/2.3.0/custom-target-3.png
  images/2.3.0/custom-target-4.png
  images/2.3.0/custom-target-5.png
  images/2.3.0/custom-target-6.png
  images/2.3.0/navigate-to-topology.png
  images/2.3.0/topology-1.png
  images/2.3.0/topology-2.png
  images/2.3.0/topology-3.png
  images/2.3.0/topology-4.png
  images/2.3.0/topology-5.png
  images/2.3.0/topology-6.png
  images/2.3.0/topology-7.png
Labels: feat, docs

#123 chore(gem): update dependencies
  Gemfile
  Gemfile.lock
Labels: chore

#126 fix(build): remove toc plugin
  Gemfile
  _config.yml
  _layouts/post.html
  _posts/2022-09-30-cryosat-blog.md
  _posts/2022-10-18-archive-on-stop.md
  _posts/2022-11-15-cryostat-release.md
  _posts/2023-05-03-agent-threads-investigation.md
  _posts/2023-05-26-cryostat-release.md
Labels: bug

#128 feat(blog): add settings blog post
  _data/authors.yaml
  _includes/tip.html
  _posts/2023-05-30-settings-page.md
  _sass/core/cryostat.scss
  images/blog/settings-page-advanced.png
  images/blog/settings-page-connectivity.png
  images/blog/settings-page-dashboard.png
  images/blog/settings-page-general.png
  images/blog/settings-page-notifications&messages.png
Labels: feat
