Repository cryostatio/cryostatio.github.io, pull requests merged in 2025-02, with the labels that each got.

#209 feat(eventtemplates): document Preset event templates
  guides/_subsections/download-edit-and-upload-a-customized-event-template.md
Labels: feat, docs

#212 chore(custom-targets): update description and images of custom target test
  guides/_subsections/create-a-custom-target.md
  images/4.0.0/custom-target-2.png
  images/4.0.0/custom-target-4.png
Labels: docs

#211 fix(rule-upload): specify that uploaded Rule JSONs should not include id
  guides/_subsections/upload-an-automated-rule.md
Labels: docs

#210 feat(expressions): document matchexpression jfrEventTypeIds function
  guides/_subsections/create-an-automated-rule.md
Labels: feat, docs

#205 chore(get-started): clean up installation, configuration, and uninstallation guide
  get-started/index.md
  images/cryostat-operatorhub-install-complete.png
  images/cryostat-operatorhub-install-in-progress.png
  images/cryostat-operatorhub-install.png
  images/cryostat-operatorhub-search.png
  images/cryostat-resource-creation.png
  images/cryostat-resource-status.png
  images/cryostat-resources-after.png
  images/cryostat-resources-before.png
  images/installed-operators.png
  images/topology-view.png
Labels: feat, docs

#201 feat(agent): describe usage of Agent init container for multi-stage container build
  get-started/index.md
Labels: feat

#208 feat(rules): document jfrEventTypeIds function
  guides/_subsections/create-an-automated-rule.md
Labels: feat, docs

#214 feat(diagnostics): Add guide for the diagnostics card
  guides/_subsections/perform-garbage-collection.md
  guides/index.md
  images/4.0.0/dashboard/add-diagnostics-card.png
  images/4.0.0/dashboard/diagnostics-card.png
Labels: feat, docs

#216 feat(agent): Add guide for the agent harvester
  guides/_subsections/configure-agent-harvester.md
  guides/index.md
Labels: feat, docs
